/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations['login_api_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_api_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations['me_api_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Change Password */
    post: operations['change_password_api_auth_password_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/password-reset/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm Reset */
    post: operations['confirm_reset_api_auth_password_reset_confirm_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/password-reset/request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Request Reset */
    post: operations['request_reset_api_auth_password_reset_request_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/barcodes/{code}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Lookup Barcode */
    get: operations['lookup_barcode_api_barcodes__code__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Config */
    get: operations['config_api_config_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/connector': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Connector Status */
    get: operations['connector_status_api_connector_get']
    put?: never
    /**
     * Create Connector Url
     * @description A new personal URL, shown once. The previous one stops working.
     */
    post: operations['create_connector_url_api_connector_post']
    /** Revoke Connector Url */
    delete: operations['revoke_connector_url_api_connector_delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/days/{day_}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Day */
    get: operations['get_day_api_days__day___get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/days/{day_}/copy': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Copy Day */
    post: operations['copy_day_api_days__day___copy_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/days/{day_}/day-type': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Set Day Type */
    put: operations['set_day_type_api_days__day___day_type_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/entries': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log Food */
    post: operations['log_food_api_entries_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/entries/{entry_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Entry */
    delete: operations['delete_entry_api_entries__entry_id__delete']
    options?: never
    head?: never
    /** Update Entry */
    patch: operations['update_entry_api_entries__entry_id__patch']
    trace?: never
  }
  '/api/entries/{entry_id}/copy': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Copy Entry */
    post: operations['copy_entry_api_entries__entry_id__copy_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/entries/{entry_id}/save-as-meal': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Save Entry As Meal */
    post: operations['save_entry_as_meal_api_entries__entry_id__save_as_meal_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/entries/{entry_id}/state': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Set Entry State */
    post: operations['set_entry_state_api_entries__entry_id__state_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Event Stream
     * @description Server-sent events for the household: `change` with the kind of thing that changed
     *     (`{"entity": "list_item"}`, `"*"` for everything). The app refetches what it shows.
     */
    get: operations['event_stream_api_events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/household': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Household */
    get: operations['get_household_api_household_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Rename Household */
    patch: operations['rename_household_api_household_patch']
    trace?: never
  }
  '/api/household/invites': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Invites */
    get: operations['list_invites_api_household_invites_get']
    put?: never
    /** Create Invite */
    post: operations['create_invite_api_household_invites_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/household/invites/{invite_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Revoke Invite */
    delete: operations['revoke_invite_api_household_invites__invite_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/invites/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Accept Invite */
    post: operations['accept_invite_api_invites_accept_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/invites/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Preview Invite */
    get: operations['preview_invite_api_invites__key__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/items': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search Items
     * @description `own=true`: only the household's own items (the foods page).
     */
    get: operations['search_items_api_items_get']
    put?: never
    /** Create Item */
    post: operations['create_item_api_items_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/items/{item_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Item */
    get: operations['get_item_api_items__item_id__get']
    /** Update Item */
    put: operations['update_item_api_items__item_id__put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/items/{item_id}/favourite': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Set Favourite */
    put: operations['set_favourite_api_items__item_id__favourite_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get List */
    get: operations['get_list_api_list_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/list/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List History
     * @description What the household has put on the list before, most used first.
     */
    get: operations['list_history_api_list_history_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/list/ops': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Apply List Ops
     * @description Apply changes in order, made online or queued offline. Each change carries the item's
     *     client-made id and the time it was made, so sending the same batch twice is harmless.
     *     Answers with each change's outcome and the list as it is now.
     */
    post: operations['apply_list_ops_api_list_ops_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Me */
    patch: operations['update_me_api_me_patch']
    trace?: never
  }
  '/api/me/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Profile */
    patch: operations['update_profile_api_me_profile_patch']
    trace?: never
  }
  '/api/online-search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search Online */
    get: operations['search_online_api_online_search_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/push': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Push Status */
    get: operations['push_status_api_push_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/push/subscriptions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Subscribe */
    post: operations['subscribe_api_push_subscriptions_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/push/subscriptions/remove': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Unsubscribe */
    post: operations['unsubscribe_api_push_subscriptions_remove_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/push/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Send Test */
    post: operations['send_test_api_push_test_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/saved-meals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Saved Meals */
    get: operations['list_saved_meals_api_saved_meals_get']
    put?: never
    /** Create Saved Meal */
    post: operations['create_saved_meal_api_saved_meals_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/saved-meals/{meal_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Saved Meal */
    delete: operations['delete_saved_meal_api_saved_meals__meal_id__delete']
    options?: never
    head?: never
    /** Update Saved Meal */
    patch: operations['update_saved_meal_api_saved_meals__meal_id__patch']
    trace?: never
  }
  '/api/stores': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Store */
    post: operations['create_store_api_stores_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/{store_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Store */
    delete: operations['delete_store_api_stores__store_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/targets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Targets */
    get: operations['get_targets_api_targets_get']
    /** Set Targets */
    put: operations['set_targets_api_targets_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/targets/week-pattern': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Set Week Pattern */
    put: operations['set_week_pattern_api_targets_week_pattern_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AcceptInviteIn */
    AcceptInviteIn: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /** Household Name */
      household_name?: string | null
      /**
       * Key
       * @description Link token or the typed code
       */
      key: string
      /**
       * Language
       * @enum {string}
       */
      language: 'de' | 'en' | 'nl'
      /** Password */
      password: string
      /** Time Zone */
      time_zone: string
    }
    /** BarcodeOut */
    BarcodeOut: {
      draft: components['schemas']['ItemDraftOut'] | null
      item: components['schemas']['ItemOut'] | null
      /**
       * Status
       * @enum {string}
       */
      status: 'item' | 'draft' | 'not_found'
    }
    /** ComponentIn */
    ComponentIn: {
      /** Amount */
      amount?: number | null
      /** Carbs */
      carbs?: number | null
      /** Fat */
      fat?: number | null
      /** Item Id */
      item_id?: string | null
      /** Kcal */
      kcal?: number | null
      /** Protein */
      protein?: number | null
      /** Quick Name */
      quick_name?: string | null
      /** Serving Count */
      serving_count?: number | null
      /** Serving Label */
      serving_label?: string | null
    }
    /** ComponentOut */
    ComponentOut: {
      /** Amount */
      amount: number | null
      /** Base Unit */
      base_unit: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Item Id */
      item_id: string | null
      /** Name */
      name: string
      nutrients: components['schemas']['NutrientsOut']
      /** Quick */
      quick: boolean
      /** Serving Count */
      serving_count: number | null
      /** Serving Label */
      serving_label: string | null
    }
    /** ConfigOut */
    ConfigOut: {
      /** Email Reset */
      email_reset: boolean
      /** Languages */
      languages: ('de' | 'en' | 'nl')[]
      /** Push Public Key */
      push_public_key: string | null
      /** Version */
      version: string
    }
    /** ConnectorCreatedOut */
    ConnectorCreatedOut: {
      /** Url */
      url: string
    }
    /** ConnectorOut */
    ConnectorOut: {
      /** Active */
      active: boolean
      /** Created At */
      created_at: string | null
      /** Last Used At */
      last_used_at: string | null
    }
    /** CopyDayIn */
    CopyDayIn: {
      /**
       * Source Day
       * Format: date
       */
      source_day: string
    }
    /** CopyEntryIn */
    CopyEntryIn: {
      /**
       * Day
       * Format: date
       */
      day: string
      /** Slot */
      slot?: ('breakfast' | 'lunch' | 'dinner' | 'snack') | null
    }
    /** DayOut */
    DayOut: {
      /**
       * Day
       * Format: date
       */
      day: string
      /** People */
      people: components['schemas']['PersonDayOut'][]
    }
    /** DayTypeIn */
    DayTypeIn: {
      /** Day Type */
      day_type: ('training' | 'rest') | null
    }
    /** EntryIn */
    EntryIn: {
      /** At */
      at?: string | null
      /** Components */
      components?: components['schemas']['ComponentIn'][]
      /**
       * Day
       * Format: date
       */
      day: string
      /**
       * Eaten Out
       * @default false
       */
      eaten_out: boolean
      /** Name */
      name?: string | null
      /**
       * Portions
       * @default 1
       */
      portions: number
      /** Saved Meal Id */
      saved_meal_id?: string | null
      /**
       * Slot
       * @enum {string}
       */
      slot: 'breakfast' | 'lunch' | 'dinner' | 'snack'
    }
    /** EntryOut */
    EntryOut: {
      /**
       * At
       * Format: time
       */
      at: string
      /** Components */
      components: components['schemas']['ComponentOut'][]
      /**
       * Day
       * Format: date
       */
      day: string
      /** Eaten Out */
      eaten_out: boolean
      /**
       * Id
       * Format: uuid
       */
      id: string
      intake: components['schemas']['TotalsOut'] | null
      /** Name */
      name: string | null
      /** Saved Meal Id */
      saved_meal_id: string | null
      /** Share */
      share: number | null
      /**
       * Slot
       * @enum {string}
       */
      slot: 'breakfast' | 'lunch' | 'dinner' | 'snack'
      /** State */
      state: ('planned' | 'logged' | 'skipped') | null
    }
    /** EntryPatchIn */
    EntryPatchIn: {
      /** At */
      at?: string | null
      /** Components */
      components?: components['schemas']['ComponentIn'][] | null
      /** Day */
      day?: string | null
      /** Eaten Out */
      eaten_out?: boolean | null
      /** Name */
      name?: string | null
      /** Slot */
      slot?: ('breakfast' | 'lunch' | 'dinner' | 'snack') | null
    }
    /** EntryStateIn */
    EntryStateIn: {
      /**
       * State
       * @enum {string}
       */
      state: 'planned' | 'logged' | 'skipped'
    }
    /** FavouriteIn */
    FavouriteIn: {
      /** On */
      on: boolean
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthOut */
    HealthOut: {
      /**
       * Database
       * @constant
       */
      database: 'ok'
      /**
       * Status
       * @constant
       */
      status: 'ok'
      /** Version */
      version: string
    }
    /** HouseholdBriefOut */
    HouseholdBriefOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
    }
    /** HouseholdOut */
    HouseholdOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Max Members */
      max_members: number
      /** Members */
      members: components['schemas']['MemberOut'][]
      /** Name */
      name: string
    }
    /** HouseholdPatch */
    HouseholdPatch: {
      /** Name */
      name: string
    }
    /** IngredientIn */
    IngredientIn: {
      /** Amount */
      amount: number
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
    }
    /** IngredientOut */
    IngredientOut: {
      /** Amount */
      amount: number
      /** Base Unit */
      base_unit: string
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Name */
      name: string
    }
    /** InviteCreateIn */
    InviteCreateIn: {
      /** Note */
      note?: string | null
    }
    /** InviteOut */
    InviteOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Note */
      note: string | null
    }
    /** InvitePreviewOut */
    InvitePreviewOut: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /** Household Name */
      household_name: string | null
      /** Inviter Name */
      inviter_name: string | null
      /**
       * Kind
       * @enum {string}
       */
      kind: 'household' | 'partner'
      /**
       * Language
       * @enum {string}
       */
      language: 'de' | 'en' | 'nl'
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'accepted' | 'revoked' | 'expired'
    }
    /** IssuedInviteOut */
    IssuedInviteOut: {
      /** Code */
      code: string
      invite: components['schemas']['InviteOut']
      /** Link */
      link: string
    }
    /** ItemDraftOut */
    ItemDraftOut: {
      /** Barcode */
      barcode: string
      /**
       * Base Unit
       * @enum {string}
       */
      base_unit: 'g' | 'ml'
      /** Brand */
      brand: string | null
      /** Category */
      category: string
      /** Complete */
      complete: boolean
      /** Image Url */
      image_url: string | null
      /** Missing */
      missing: string[]
      /** Names */
      names: {
        [key: string]: string
      }
      nutrients: components['schemas']['NutrientsOut']
      /** Package Size */
      package_size: number | null
      /** Servings */
      servings: components['schemas']['ServingOut'][]
    }
    /** ItemIn */
    ItemIn: {
      /** Barcodes */
      barcodes?: string[]
      /**
       * Base Unit
       * @default g
       * @enum {string}
       */
      base_unit: 'g' | 'ml'
      /** Brand */
      brand?: string | null
      /**
       * Category
       * @default other
       * @enum {string}
       */
      category:
        | 'produce'
        | 'bakery'
        | 'meat_fish'
        | 'dairy_eggs'
        | 'dry_goods'
        | 'canned'
        | 'frozen'
        | 'oils_fats'
        | 'spices_condiments'
        | 'sweets_snacks'
        | 'drinks'
        | 'household'
        | 'personal_care'
        | 'other'
      /** Image Url */
      image_url?: string | null
      /** Names */
      names: {
        [key: string]: string | null
      }
      nutrients?: components['schemas']['NutrientsIn']
      /** Package Size */
      package_size?: number | null
      /** Servings */
      servings?: components['schemas']['ServingIn'][]
      /**
       * Source
       * @default custom
       * @enum {string}
       */
      source: 'custom' | 'off'
      /**
       * Tracking Mode
       * @default counted
       * @enum {string}
       */
      tracking_mode: 'counted' | 'status'
    }
    /** ItemOut */
    ItemOut: {
      /** Barcodes */
      barcodes: string[]
      /**
       * Base Unit
       * @enum {string}
       */
      base_unit: 'g' | 'ml'
      /** Brand */
      brand: string | null
      /** Category */
      category: string
      /** Favourite */
      favourite: boolean
      /** Generic */
      generic: boolean
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Image Url */
      image_url: string | null
      /** Name */
      name: string
      /** Names */
      names: {
        [key: string]: string | null
      }
      nutrients: components['schemas']['NutrientsOut']
      /** Package Size */
      package_size: number | null
      /** Servings */
      servings: components['schemas']['ServingOut'][]
      /** Source */
      source: string
      /**
       * Tracking Mode
       * @enum {string}
       */
      tracking_mode: 'counted' | 'status'
    }
    /**
     * ListFieldsIn
     * @description Only the fields that are sent are changed; send null to clear quantity or store.
     */
    ListFieldsIn: {
      /** Category */
      category?: string | null
      /** Checked */
      checked?: boolean | null
      /** Item Id */
      item_id?: string | null
      /**
       * Parse
       * @description On add: split a quantity such as '2' or '500 g' off the text.
       */
      parse?: boolean | null
      /** Quantity */
      quantity?: string | null
      /** Store Id */
      store_id?: string | null
      /** Text */
      text?: string | null
    }
    /** ListItemOut */
    ListItemOut: {
      /** Category */
      category: string
      /** Checked */
      checked: boolean
      /** Checked At */
      checked_at: string | null
      /** Checked By */
      checked_by: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Created By */
      created_by: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Item Id */
      item_id: string | null
      /** Quantity */
      quantity: string | null
      /** Store Id */
      store_id: string | null
      /** Text */
      text: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /** ListMemoryOut */
    ListMemoryOut: {
      /** Category */
      category: string
      /** Item Id */
      item_id: string | null
      /** Store Id */
      store_id: string | null
      /** Text */
      text: string
      /** Uses */
      uses: number
    }
    /** ListOpIn */
    ListOpIn: {
      /**
       * At
       * @description When the change was made.
       */
      at?: string | null
      fields?: components['schemas']['ListFieldsIn']
      /**
       * Id
       * Format: uuid
       * @description The list item's id, made by the client on add.
       */
      id: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'add' | 'update' | 'remove'
    }
    /** ListOpResultOut */
    ListOpResultOut: {
      /** Code */
      code: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Status
       * @enum {string}
       */
      status: 'applied' | 'unchanged' | 'removed' | 'not_found' | 'invalid'
    }
    /** ListOpsIn */
    ListOpsIn: {
      /** Ops */
      ops: components['schemas']['ListOpIn'][]
    }
    /** ListOpsOut */
    ListOpsOut: {
      list: components['schemas']['ListOut']
      /** Results */
      results: components['schemas']['ListOpResultOut'][]
    }
    /** ListOut */
    ListOut: {
      /** Items */
      items: components['schemas']['ListItemOut'][]
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string
      /** Stores */
      stores: components['schemas']['StoreOut'][]
    }
    /** LoginIn */
    LoginIn: {
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /** MeOut */
    MeOut: {
      /** Csrf Token */
      csrf_token: string
      household: components['schemas']['HouseholdBriefOut']
      profile: components['schemas']['ProfileOut']
      user: components['schemas']['UserOut']
    }
    /** MePatch */
    MePatch: {
      /** Display Name */
      display_name?: string | null
      /** Language */
      language?: ('de' | 'en' | 'nl') | null
      /** Time Zone */
      time_zone?: string | null
    }
    /** MemberOut */
    MemberOut: {
      /** Display Name */
      display_name: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Me */
      is_me: boolean
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string
    }
    /** NutrientsIn */
    NutrientsIn: {
      /** Alcohol */
      alcohol?: number | null
      /** Carbs */
      carbs?: number | null
      /** Fat */
      fat?: number | null
      /** Fibre */
      fibre?: number | null
      /** Kcal */
      kcal?: number | null
      /** Protein */
      protein?: number | null
      /** Salt */
      salt?: number | null
      /** Sat Fat */
      sat_fat?: number | null
      /** Sugar */
      sugar?: number | null
    }
    /** NutrientsOut */
    NutrientsOut: {
      /** Alcohol */
      alcohol: number | null
      /** Carbs */
      carbs: number | null
      /** Fat */
      fat: number | null
      /** Fibre */
      fibre: number | null
      /** Kcal */
      kcal: number | null
      /** Protein */
      protein: number | null
      /** Salt */
      salt: number | null
      /** Sat Fat */
      sat_fat: number | null
      /** Sugar */
      sugar: number | null
    }
    /** PasswordChangeIn */
    PasswordChangeIn: {
      /** Current Password */
      current_password: string
      /** New Password */
      new_password: string
    }
    /** PersonDayOut */
    PersonDayOut: {
      /**
       * Day Type
       * @enum {string}
       */
      day_type: 'training' | 'rest'
      /** Display Name */
      display_name: string
      /** Entries */
      entries: components['schemas']['EntryOut'][]
      /** Is Me */
      is_me: boolean
      logged: components['schemas']['TotalsOut']
      planned: components['schemas']['TotalsOut']
      projection: components['schemas']['TargetsOut'] | null
      remaining: components['schemas']['TargetsOut'] | null
      targets: components['schemas']['TargetsOut'] | null
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
    }
    /** ProfileOut */
    ProfileOut: {
      /** Push Offers */
      push_offers: boolean
      /** Share Ai Usage */
      share_ai_usage: boolean
      /** Show Body */
      show_body: boolean
      /** Show Workouts */
      show_workouts: boolean
      /**
       * Start Screen
       * @enum {string}
       */
      start_screen: 'today' | 'list'
    }
    /** ProfilePatch */
    ProfilePatch: {
      /** Push Offers */
      push_offers?: boolean | null
      /** Share Ai Usage */
      share_ai_usage?: boolean | null
      /** Show Body */
      show_body?: boolean | null
      /** Show Workouts */
      show_workouts?: boolean | null
      /** Start Screen */
      start_screen?: ('today' | 'list') | null
    }
    /** PushKeys */
    PushKeys: {
      /** Auth */
      auth: string
      /** P256Dh */
      p256dh: string
    }
    /** PushStatusOut */
    PushStatusOut: {
      /** Configured */
      configured: boolean
      /** Devices */
      devices: number
      /** Public Key */
      public_key: string | null
    }
    /** PushSubscriptionIn */
    PushSubscriptionIn: {
      /** Endpoint */
      endpoint: string
      keys: components['schemas']['PushKeys']
    }
    /** PushUnsubscribeIn */
    PushUnsubscribeIn: {
      /** Endpoint */
      endpoint: string
    }
    /** ResetConfirmIn */
    ResetConfirmIn: {
      /** Password */
      password: string
      /** Token */
      token: string
    }
    /** ResetRequestIn */
    ResetRequestIn: {
      /** Email */
      email: string
    }
    /** SaveAsMealIn */
    SaveAsMealIn: {
      /** Name */
      name?: string | null
    }
    /** SavedMealIn */
    SavedMealIn: {
      /** Ingredients */
      ingredients: components['schemas']['IngredientIn'][]
      /** Name */
      name: string
    }
    /** SavedMealOut */
    SavedMealOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Ingredients */
      ingredients: components['schemas']['IngredientOut'][]
      /** Name */
      name: string
      per_serving: components['schemas']['TotalsOut']
    }
    /** SavedMealPatchIn */
    SavedMealPatchIn: {
      /** Ingredients */
      ingredients?: components['schemas']['IngredientIn'][] | null
      /** Name */
      name?: string | null
    }
    /** ServingIn */
    ServingIn: {
      /** Amount */
      amount: number
      /** Label */
      label: string
    }
    /** ServingOut */
    ServingOut: {
      /** Amount */
      amount: number
      /** Label */
      label: string
    }
    /** StoreIn */
    StoreIn: {
      /** Name */
      name: string
    }
    /** StoreOut */
    StoreOut: {
      /** Custom */
      custom: boolean
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Key */
      key: string | null
      /** Name */
      name: string | null
    }
    /** TargetPlanOut */
    TargetPlanOut: {
      /** History */
      history: components['schemas']['TargetSetOut'][]
      /** Week Pattern */
      week_pattern: string
    }
    /** TargetSetOut */
    TargetSetOut: {
      /**
       * Day Type
       * @enum {string}
       */
      day_type: 'training' | 'rest'
      targets: components['schemas']['TargetsOut']
      /**
       * Valid From
       * Format: date
       */
      valid_from: string
    }
    /** TargetsIn */
    TargetsIn: {
      /** Carbs */
      carbs?: number | null
      /** Day Types */
      day_types: ('training' | 'rest')[]
      /** Fat */
      fat?: number | null
      /** Kcal */
      kcal?: number | null
      /** Protein */
      protein?: number | null
      /** Valid From */
      valid_from?: string | null
    }
    /** TargetsOut */
    TargetsOut: {
      /** Carbs */
      carbs: number | null
      /** Fat */
      fat: number | null
      /** Kcal */
      kcal: number | null
      /** Protein */
      protein: number | null
    }
    /** TotalsOut */
    TotalsOut: {
      /** Incomplete */
      incomplete: string[]
      values: components['schemas']['NutrientsOut']
    }
    /** UserOut */
    UserOut: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Admin */
      is_admin: boolean
      /**
       * Language
       * @enum {string}
       */
      language: 'de' | 'en' | 'nl'
      /** Time Zone */
      time_zone: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** WeekPatternIn */
    WeekPatternIn: {
      /** Pattern */
      pattern: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login_api_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me_api_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
    }
  }
  change_password_api_auth_password_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChangeIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  confirm_reset_api_auth_password_reset_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetConfirmIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  request_reset_api_auth_password_reset_request_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetRequestIn']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  lookup_barcode_api_barcodes__code__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        code: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BarcodeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  config_api_config_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConfigOut']
        }
      }
    }
  }
  connector_status_api_connector_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConnectorOut']
        }
      }
    }
  }
  create_connector_url_api_connector_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConnectorCreatedOut']
        }
      }
    }
  }
  revoke_connector_url_api_connector_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_day_api_days__day___get: {
    parameters: {
      query?: never
      header?: never
      path: {
        day_: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DayOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  copy_day_api_days__day___copy_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        day_: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CopyDayIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntryOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_day_type_api_days__day___day_type_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        day_: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DayTypeIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  log_food_api_entries_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EntryIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntryOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_entry_api_entries__entry_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        entry_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_entry_api_entries__entry_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        entry_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EntryPatchIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntryOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  copy_entry_api_entries__entry_id__copy_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        entry_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CopyEntryIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntryOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  save_entry_as_meal_api_entries__entry_id__save_as_meal_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        entry_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveAsMealIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SavedMealOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_entry_state_api_entries__entry_id__state_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        entry_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EntryStateIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntryOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  event_stream_api_events_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': unknown
        }
      }
    }
  }
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthOut']
        }
      }
    }
  }
  get_household_api_household_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HouseholdOut']
        }
      }
    }
  }
  rename_household_api_household_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['HouseholdPatch']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HouseholdOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_invites_api_household_invites_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InviteOut'][]
        }
      }
    }
  }
  create_invite_api_household_invites_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InviteCreateIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IssuedInviteOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  revoke_invite_api_household_invites__invite_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        invite_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  accept_invite_api_invites_accept_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AcceptInviteIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  preview_invite_api_invites__key__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitePreviewOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  search_items_api_items_get: {
    parameters: {
      query?: {
        q?: string
        limit?: number
        own?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ItemOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_item_api_items_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ItemIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ItemOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_item_api_items__item_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ItemOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_item_api_items__item_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ItemIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ItemOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_favourite_api_items__item_id__favourite_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FavouriteIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_list_api_list_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListOut']
        }
      }
    }
  }
  list_history_api_list_history_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListMemoryOut'][]
        }
      }
    }
  }
  apply_list_ops_api_list_ops_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ListOpsIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListOpsOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_me_api_me_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MePatch']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_profile_api_me_profile_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfilePatch']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  search_online_api_online_search_get: {
    parameters: {
      query: {
        q: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ItemDraftOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  push_status_api_push_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PushStatusOut']
        }
      }
    }
  }
  subscribe_api_push_subscriptions_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PushSubscriptionIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  unsubscribe_api_push_subscriptions_remove_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PushUnsubscribeIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  send_test_api_push_test_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  list_saved_meals_api_saved_meals_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SavedMealOut'][]
        }
      }
    }
  }
  create_saved_meal_api_saved_meals_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SavedMealIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SavedMealOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_saved_meal_api_saved_meals__meal_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        meal_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_saved_meal_api_saved_meals__meal_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        meal_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SavedMealPatchIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SavedMealOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_store_api_stores_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StoreOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_store_api_stores__store_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        store_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_targets_api_targets_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TargetPlanOut']
        }
      }
    }
  }
  set_targets_api_targets_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TargetsIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TargetPlanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_week_pattern_api_targets_week_pattern_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WeekPatternIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TargetPlanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
