/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations['login_api_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_api_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations['me_api_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Change Password */
    post: operations['change_password_api_auth_password_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/password-reset/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm Reset */
    post: operations['confirm_reset_api_auth_password_reset_confirm_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/password-reset/request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Request Reset */
    post: operations['request_reset_api_auth_password_reset_request_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Config */
    get: operations['config_api_config_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/household': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Household */
    get: operations['get_household_api_household_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Rename Household */
    patch: operations['rename_household_api_household_patch']
    trace?: never
  }
  '/api/household/invites': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Invites */
    get: operations['list_invites_api_household_invites_get']
    put?: never
    /** Create Invite */
    post: operations['create_invite_api_household_invites_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/household/invites/{invite_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Revoke Invite */
    delete: operations['revoke_invite_api_household_invites__invite_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/invites/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Accept Invite */
    post: operations['accept_invite_api_invites_accept_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/invites/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Preview Invite */
    get: operations['preview_invite_api_invites__key__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Me */
    patch: operations['update_me_api_me_patch']
    trace?: never
  }
  '/api/me/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Profile */
    patch: operations['update_profile_api_me_profile_patch']
    trace?: never
  }
  '/api/push': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Push Status */
    get: operations['push_status_api_push_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/push/subscriptions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Subscribe */
    post: operations['subscribe_api_push_subscriptions_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/push/subscriptions/remove': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Unsubscribe */
    post: operations['unsubscribe_api_push_subscriptions_remove_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/push/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Send Test */
    post: operations['send_test_api_push_test_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AcceptInviteIn */
    AcceptInviteIn: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /** Household Name */
      household_name?: string | null
      /**
       * Key
       * @description Link token or the typed code
       */
      key: string
      /**
       * Language
       * @enum {string}
       */
      language: 'de' | 'en' | 'nl'
      /** Password */
      password: string
      /** Time Zone */
      time_zone: string
    }
    /** ConfigOut */
    ConfigOut: {
      /** Email Reset */
      email_reset: boolean
      /** Languages */
      languages: ('de' | 'en' | 'nl')[]
      /** Push Public Key */
      push_public_key: string | null
      /** Version */
      version: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthOut */
    HealthOut: {
      /**
       * Database
       * @constant
       */
      database: 'ok'
      /**
       * Status
       * @constant
       */
      status: 'ok'
      /** Version */
      version: string
    }
    /** HouseholdBriefOut */
    HouseholdBriefOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
    }
    /** HouseholdOut */
    HouseholdOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Max Members */
      max_members: number
      /** Members */
      members: components['schemas']['MemberOut'][]
      /** Name */
      name: string
    }
    /** HouseholdPatch */
    HouseholdPatch: {
      /** Name */
      name: string
    }
    /** InviteCreateIn */
    InviteCreateIn: {
      /** Note */
      note?: string | null
    }
    /** InviteOut */
    InviteOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Note */
      note: string | null
    }
    /** InvitePreviewOut */
    InvitePreviewOut: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /** Household Name */
      household_name: string | null
      /** Inviter Name */
      inviter_name: string | null
      /**
       * Kind
       * @enum {string}
       */
      kind: 'household' | 'partner'
      /**
       * Language
       * @enum {string}
       */
      language: 'de' | 'en' | 'nl'
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'accepted' | 'revoked' | 'expired'
    }
    /** IssuedInviteOut */
    IssuedInviteOut: {
      /** Code */
      code: string
      invite: components['schemas']['InviteOut']
      /** Link */
      link: string
    }
    /** LoginIn */
    LoginIn: {
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /** MeOut */
    MeOut: {
      /** Csrf Token */
      csrf_token: string
      household: components['schemas']['HouseholdBriefOut']
      profile: components['schemas']['ProfileOut']
      user: components['schemas']['UserOut']
    }
    /** MePatch */
    MePatch: {
      /** Display Name */
      display_name?: string | null
      /** Language */
      language?: ('de' | 'en' | 'nl') | null
      /** Time Zone */
      time_zone?: string | null
    }
    /** MemberOut */
    MemberOut: {
      /** Display Name */
      display_name: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Me */
      is_me: boolean
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string
    }
    /** PasswordChangeIn */
    PasswordChangeIn: {
      /** Current Password */
      current_password: string
      /** New Password */
      new_password: string
    }
    /** ProfileOut */
    ProfileOut: {
      /** Push Offers */
      push_offers: boolean
      /** Share Ai Usage */
      share_ai_usage: boolean
      /** Show Body */
      show_body: boolean
      /** Show Workouts */
      show_workouts: boolean
      /**
       * Start Screen
       * @enum {string}
       */
      start_screen: 'today' | 'list'
    }
    /** ProfilePatch */
    ProfilePatch: {
      /** Push Offers */
      push_offers?: boolean | null
      /** Share Ai Usage */
      share_ai_usage?: boolean | null
      /** Show Body */
      show_body?: boolean | null
      /** Show Workouts */
      show_workouts?: boolean | null
      /** Start Screen */
      start_screen?: ('today' | 'list') | null
    }
    /** PushKeys */
    PushKeys: {
      /** Auth */
      auth: string
      /** P256Dh */
      p256dh: string
    }
    /** PushStatusOut */
    PushStatusOut: {
      /** Configured */
      configured: boolean
      /** Devices */
      devices: number
      /** Public Key */
      public_key: string | null
    }
    /** PushSubscriptionIn */
    PushSubscriptionIn: {
      /** Endpoint */
      endpoint: string
      keys: components['schemas']['PushKeys']
    }
    /** PushUnsubscribeIn */
    PushUnsubscribeIn: {
      /** Endpoint */
      endpoint: string
    }
    /** ResetConfirmIn */
    ResetConfirmIn: {
      /** Password */
      password: string
      /** Token */
      token: string
    }
    /** ResetRequestIn */
    ResetRequestIn: {
      /** Email */
      email: string
    }
    /** UserOut */
    UserOut: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Admin */
      is_admin: boolean
      /**
       * Language
       * @enum {string}
       */
      language: 'de' | 'en' | 'nl'
      /** Time Zone */
      time_zone: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login_api_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me_api_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
    }
  }
  change_password_api_auth_password_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChangeIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  confirm_reset_api_auth_password_reset_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetConfirmIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  request_reset_api_auth_password_reset_request_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetRequestIn']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  config_api_config_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConfigOut']
        }
      }
    }
  }
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthOut']
        }
      }
    }
  }
  get_household_api_household_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HouseholdOut']
        }
      }
    }
  }
  rename_household_api_household_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['HouseholdPatch']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HouseholdOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_invites_api_household_invites_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InviteOut'][]
        }
      }
    }
  }
  create_invite_api_household_invites_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InviteCreateIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IssuedInviteOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  revoke_invite_api_household_invites__invite_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        invite_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  accept_invite_api_invites_accept_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AcceptInviteIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  preview_invite_api_invites__key__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitePreviewOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_me_api_me_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MePatch']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_profile_api_me_profile_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfilePatch']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  push_status_api_push_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PushStatusOut']
        }
      }
    }
  }
  subscribe_api_push_subscriptions_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PushSubscriptionIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  unsubscribe_api_push_subscriptions_remove_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PushUnsubscribeIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  send_test_api_push_test_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
