"""shopping list, stores, list memory

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 20:38:31.254757
"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

BUILTIN_STORES = ("aldi", "lidl", "edeka", "rewe", "netto", "penny", "dm", "other")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=40), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(household_id IS NULL AND key IS NOT NULL) OR (household_id IS NOT NULL AND name IS NOT NULL)",
            name=op.f("ck_store_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_store_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store")),
        sa.UniqueConstraint("key", name=op.f("uq_store_key")),
    )
    op.create_index(op.f("ix_store_household_id"), "store", ["household_id"], unique=False)
    op.create_index(
        "uq_store_household_name",
        "store",
        ["household_id", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("household_id IS NOT NULL"),
    )
    op.create_table(
        "list_memory",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("text", sa.String(length=120), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=True),
        sa.Column("uses", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "category IN ('produce', 'bakery', 'meat_fish', 'dairy_eggs', 'dry_goods', 'canned', 'frozen', 'oils_fats', 'spices_condiments', 'sweets_snacks', 'drinks', 'household', 'personal_care', 'other')",
            name=op.f("ck_list_memory_category"),
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_list_memory_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], name=op.f("fk_list_memory_item_id_item"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
            name=op.f("fk_list_memory_store_id_store"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_list_memory")),
        sa.UniqueConstraint("household_id", "key", name=op.f("uq_list_memory_household_id")),
    )
    op.create_table(
        "shopping_list_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(length=120), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.String(length=40), nullable=True),
        sa.Column("store_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("checked", sa.Boolean(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_by", sa.Uuid(), nullable=True),
        sa.Column("origin", sa.String(length=12), nullable=False),
        sa.Column("field_times", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "category IN ('produce', 'bakery', 'meat_fish', 'dairy_eggs', 'dry_goods', 'canned', 'frozen', 'oils_fats', 'spices_condiments', 'sweets_snacks', 'drinks', 'household', 'personal_care', 'other')",
            name=op.f("ck_shopping_list_item_category"),
        ),
        sa.ForeignKeyConstraint(
            ["checked_by"],
            ["user_account.id"],
            name=op.f("fk_shopping_list_item_checked_by_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_account.id"],
            name=op.f("fk_shopping_list_item_created_by_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user_account.id"],
            name=op.f("fk_shopping_list_item_deleted_by_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_shopping_list_item_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_shopping_list_item_item_id_item"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
            name=op.f("fk_shopping_list_item_store_id_store"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopping_list_item")),
    )
    op.create_index(
        "ix_shopping_list_item_open",
        "shopping_list_item",
        ["household_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
    # Built-in stores: global rows with stable ids, so every instance agrees on them.
    store = sa.table(
        "store",
        sa.column("id", sa.Uuid()),
        sa.column("key", sa.String()),
        sa.column("position", sa.Integer()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        store,
        [
            {
                "id": uuid.uuid5(uuid.NAMESPACE_URL, f"mahlzeit:store:{key}"),
                "key": key,
                "position": i,
                "created_at": datetime.now(UTC),
            }
            for i, key in enumerate(BUILTIN_STORES)
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_shopping_list_item_open",
        table_name="shopping_list_item",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("shopping_list_item")
    op.drop_table("list_memory")
    op.drop_index(
        "uq_store_household_name",
        table_name="store",
        postgresql_where=sa.text("household_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_store_household_id"), table_name="store")
    op.drop_table("store")
    # ### end Alembic commands ###
