"""purchases and stock

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-07 13:42:24.455297
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pantry_check",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checked_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "category IN ('produce', 'bakery', 'meat_fish', 'dairy_eggs', 'dry_goods', 'canned', 'frozen', 'oils_fats', 'spices_condiments', 'sweets_snacks', 'drinks', 'household', 'personal_care', 'other')",
            name=op.f("ck_pantry_check_category"),
        ),
        sa.ForeignKeyConstraint(
            ["checked_by"],
            ["user_account.id"],
            name=op.f("fk_pantry_check_checked_by_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_pantry_check_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("household_id", "category", name=op.f("pk_pantry_check")),
    )
    op.create_table(
        "purchase",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=True),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_account.id"],
            name=op.f("fk_purchase_created_by_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_purchase_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["store.id"], name=op.f("fk_purchase_store_id_store"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase")),
    )
    op.create_index("ix_purchase_household_day", "purchase", ["household_id", "day"], unique=False)
    op.create_table(
        "purchase_line",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("purchase_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.String(length=120), nullable=False),
        sa.Column("quantity", sa.String(length=40), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("price_cents", sa.Integer(), nullable=True),
        sa.Column("list_item_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "amount IS NULL OR amount > 0", name=op.f("ck_purchase_line_amount_positive")
        ),
        sa.CheckConstraint(
            "price_cents IS NULL OR price_cents >= 0",
            name=op.f("ck_purchase_line_price_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_purchase_line_item_id_item"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchase.id"],
            name=op.f("fk_purchase_line_purchase_id_purchase"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_line")),
    )
    op.create_index(op.f("ix_purchase_line_item_id"), "purchase_line", ["item_id"], unique=False)
    op.create_index(
        op.f("ix_purchase_line_purchase_id"), "purchase_line", ["purchase_id"], unique=False
    )
    op.create_table(
        "stock_movement",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(length=12), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "reason IN ('purchase', 'consumption', 'correction', 'waste')",
            name=op.f("ck_stock_movement_reason"),
        ),
        sa.CheckConstraint(
            "source IN ('purchase', 'entry', 'shortfall', 'pantry', 'manual')",
            name=op.f("ck_stock_movement_source"),
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_stock_movement_amount_not_zero")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_account.id"],
            name=op.f("fk_stock_movement_created_by_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_stock_movement_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_stock_movement_item_id_item"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movement")),
    )
    op.create_index(
        "ix_stock_movement_household_day", "stock_movement", ["household_id", "day"], unique=False
    )
    op.create_index(
        "ix_stock_movement_household_item",
        "stock_movement",
        ["household_id", "item_id"],
        unique=False,
    )
    op.create_index("ix_stock_movement_source_id", "stock_movement", ["source_id"], unique=False)
    op.create_table(
        "stock_status",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=4), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "mode IS NULL OR mode IN ('counted', 'status')", name=op.f("ck_stock_status_mode")
        ),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('ok', 'low', 'out')", name=op.f("ck_stock_status_status")
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_stock_status_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], name=op.f("fk_stock_status_item_id_item"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user_account.id"],
            name=op.f("fk_stock_status_updated_by_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("household_id", "item_id", name=op.f("pk_stock_status")),
    )
    op.add_column(
        "profile", sa.Column("list_plan_days", sa.Integer(), server_default="3", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "list_plan_days")
    op.drop_table("stock_status")
    op.drop_index("ix_stock_movement_source_id", table_name="stock_movement")
    op.drop_index("ix_stock_movement_household_item", table_name="stock_movement")
    op.drop_index("ix_stock_movement_household_day", table_name="stock_movement")
    op.drop_table("stock_movement")
    op.drop_index(op.f("ix_purchase_line_purchase_id"), table_name="purchase_line")
    op.drop_index(op.f("ix_purchase_line_item_id"), table_name="purchase_line")
    op.drop_table("purchase_line")
    op.drop_index("ix_purchase_household_day", table_name="purchase")
    op.drop_table("purchase")
    op.drop_table("pantry_check")
    # ### end Alembic commands ###
