"""offers and exact amounts

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-07 10:34:02.368040
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("from_user_id", sa.Uuid(), nullable=False),
        sa.Column("to_user_id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=True),
        sa.Column("counter_of_id", sa.Uuid(), nullable=True),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("slot", sa.String(length=10), nullable=False),
        sa.Column("share", sa.Float(), nullable=False),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "slot IN ('breakfast', 'lunch', 'dinner', 'snack')", name=op.f("ck_offer_slot")
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'accepted', 'declined', 'countered', 'withdrawn', 'expired')",
            name=op.f("ck_offer_state"),
        ),
        sa.CheckConstraint("from_user_id <> to_user_id", name=op.f("ck_offer_not_to_self")),
        sa.CheckConstraint("share > 0 AND share < 1", name=op.f("ck_offer_share")),
        sa.ForeignKeyConstraint(
            ["counter_of_id"],
            ["offer.id"],
            name=op.f("fk_offer_counter_of_id_offer"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["meal_entry.id"],
            name=op.f("fk_offer_entry_id_meal_entry"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["user_account.id"],
            name=op.f("fk_offer_from_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_offer_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"],
            ["user_account.id"],
            name=op.f("fk_offer_to_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer")),
    )
    op.create_index(op.f("ix_offer_entry_id"), "offer", ["entry_id"], unique=False)
    op.create_index("ix_offer_household_day", "offer", ["household_id", "day"], unique=False)
    op.create_index("ix_offer_to_user_state", "offer", ["to_user_id", "state"], unique=False)
    op.create_table(
        "meal_exact_amount",
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_meal_exact_amount_amount_positive")),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["meal_component.id"],
            name=op.f("fk_meal_exact_amount_component_id_meal_component"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["meal_participant.id"],
            name=op.f("fk_meal_exact_amount_participant_id_meal_participant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "participant_id", "component_id", name=op.f("pk_meal_exact_amount")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meal_exact_amount")
    op.drop_index("ix_offer_to_user_state", table_name="offer")
    op.drop_index("ix_offer_household_day", table_name="offer")
    op.drop_index(op.f("ix_offer_entry_id"), table_name="offer")
    op.drop_table("offer")
    # ### end Alembic commands ###
